### PR TITLE
Add : Stripe Payment gateway added

### PR DESCRIPTION
**Pull request by Rits1272**
## Pull request checklist
# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have deployed locally to see if issue is fixed
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Assigned current issues or new issues to PR

### CODE REVIEW

**Comment by Rits1272** [comment]
Solved issue #9

**Comment by krritik** [comment]
ok, I will try to review it by tonight

**Comment by krritik** [comment]
Can you explain or show, what you did and what libraries/functionalities you used for it? It will be a great help in reviewing it.

**Comment by Rits1272** [comment]
Hello @krritik! I have created a new app **'payments'**. In the app I have created a url file that will direct to the payment. Earlier when we book a ticket it just redirects to the book_verify page. Between these I have added a **stripe payment** which after completion will redirect to the book_verify page.
I have created a **payments.html** template file which needs some designing for which we can open a new issue after merge.

**Comment by krritik** [comment]
ok, I will review it tomorrow

**Comment by krritik** [comment]
Screenshot from 2019-12-09 14-09-38
what does dotenv do?

**Comment by Rits1272** [comment]
**dotenv** is a python module that **exports the api key stored in the .env file to the settings.py file**. A quick note : I just renamed the stripe.env file to .env file.

**Comment by krritik** [comment]
update the requirements.txt with the correct version of dotenv. It will make it easier for others to install it.
Also, can you elaborate on how you used dotenv for payments?

**Comment by Rits1272** [comment]
I have updated requirements.txt file

**Comment by Rits1272** [comment]
@krritik  please review!

**Comment by krritik** [comment]
Next time, do write things which are helpful for testing like how to generate keys and sample cards ids which can be used for testing. It saves time.

**Pull request merged**
