### PR TITLE
Origin/krritik_temp

### PR DESCRIPTION
**Pull request by mac912**
## Pull request checklist
# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have deployed locally to see if issue is fixed
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] Assigned current issues or new issues to PR

### CODE REVIEW

**Comment by krritik** [comment]
Resolve the conflict and also update the local server link:127.0.0.1/home to 127.0.0.1/ in the readme

**Comment by krritik** [comment]
And also I would suggest instead of removing the link "/home" from the URL. Just add another url for just "/" , because removing the home URL will break the code in some parts.

**Comment by mac912** [comment]
1. path('/', views.home, name='home')
 2.path('home/', views.home, name='home'),
like this?
should I keep both the urls

**Comment by krritik** [comment]
Yes keep both urls

**Comment by krritik** [comment]
already done

**Pull request closed without merging**
