### PR TITLE
staff pages layout changed

### PR DESCRIPTION
**Pull request by Sahilbabani**
layout changed
added two files templetes/base.html and templetes/base_html

## Pull request checklist
# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have deployed locally to see if issue is fixed
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] Assigned current issues or new issues to PR
added two files 
-[] templetes/admin/base.html
-[] templetes/admin/base_site.html
Screenshot (27)
Screenshot (28)

Screenshot (29)
Screenshot (30)
Screenshot (31)

### CODE REVIEW

**Comment by krritik** [comment]
will review it asap

**Comment by krritik** [comment]
Remove the useful links, as they are of no use to staff login.

**Comment by Sahilbabani** [comment]
Ok , else everything is fine?

**Comment by krritik** [comment]
footer is not at the end but you can resolve that later when you will be improving the layout. Rest is fine for now

**Comment by Sahilbabani** [comment]
done

**Comment by krritik** [comment]
solved #22

**Pull request merged**
