### PR TITLE
Staff and superuser error message in the visitor's login page. 

### PR DESCRIPTION
**Pull request by Rits1272**
## Pull request checklist
# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have deployed locally to see if issue is fixed
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Assigned current issues or new issues to PR

### CODE REVIEW

**Comment by Rits1272** [comment]
Solves issue #29. Please review @krritik

**Comment by krritik** [comment]
I will review it asap

**Comment by Rits1272** [comment]
Please review @krritik . I have resolved the conflicts

**Comment by krritik** [comment]
will review as soon as I get time

**Pull request merged**
