### PR TITLE
Frontend Design

### PR DESCRIPTION
**Pull request by Suchana34**
## Pull request checklist
# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have deployed locally to see if issue is fixed
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Assigned current issues or new issues to PR

### CODE REVIEW

**Comment by Rits1272** [comment]
I guess, you should close PR #36

**Comment by Suchana34** [comment]
> I guess, you should close PR #36

Okay, thanks.

**Comment by Suchana34** [comment]
I have edited most of the frontend, but still few changes are left, like the login form, change password form, and responsive design. I will continue working on it, just review the design I gave.

**Comment by krritik** [comment]
Till now, it looks cool. I actually loved it. :heart_eyes: 
Screenshot from 2019-12-20 19-12-35
A few suggestions, "the size of start date and end date are very small" and there are also some other minute changes possible(sizes of context, the date should be in the middle of the search box)
Screenshot from 2019-12-20 19-17-10
You can also improve this table.

Since you are not complete with the design, I would wait for your completion. So when you are done, Ping me.

**Comment by Rits1272** [comment]
Design is actually quite good :)

**Comment by Suchana34** [comment]
Thank you @krritik  @Rits1272  :)
I have noted the suggestions and soon work on it.

**Comment by Suchana34** [comment]
I have redesigned the tables and made the pages responsive.

**Comment by Suchana34** [comment]
Please review @krritik .

**Comment by Suchana34** [comment]
Screenshot (297)

**Comment by Suchana34** [comment]
Screenshot (298)

**Comment by Suchana34** [comment]
Screenshot (299)

**Comment by Suchana34** [comment]
Screenshot (303)

**Comment by krritik** [comment]
cool
It looks good
I will review it asap
But I have some urgent work till 27 so there might be some delay in merging PR

**Comment by Suchana34** [comment]
Okay, sure.

**Comment by Suchana34** [comment]
Hello @krritik since 2nd Jan is the last day of pr, let me know before 30th what further changes I need to do.

**Comment by krritik** [comment]
Screenshot from 2019-12-30 01-56-08
Screenshot from 2019-12-30 01-56-33
Staff login is still the old, you can create an issue for it and later work on it. So that I can merge this without even updating staff login or otherwise improve its layout too.

Screenshot from 2019-12-30 01-55-58
The font size of a few things like Username, Email are still very small, can increase the size of them a bit.(At some other places too, the font size is a bit smaller).

Screenshot from 2019-12-30 01-55-22
You can change the color of the "Edit" button, but it is not a much problem(just recommendation).

**Comment by krritik** [comment]
@Suchana34 
Do the necessary changes and I will try to merge it asap. Just ping me once in slack, when you have done this.

**Comment by Suchana34** [comment]
Hello @krritik, I have fixed the size of the text of the forms. Since I didn't know much about Django Form widgets then, so I couldn't modify them earlier, now it is solved :) 
I also edited the error messages.

**Comment by Suchana34** [comment]
And I will create an issue now for the staff side and work on it soon.

**Comment by Suchana34** [comment]
Screenshot (360)

**Comment by Suchana34** [comment]
Screenshot (361)

**Comment by krritik** [comment]
looks fine for now
also always assign the issue to PR. It helps in future.

**Comment by krritik** [comment]
solved issue #5

**Pull request merged**
