### PR TITLE
front-end home,login,signup page

### PR DESCRIPTION
**Pull request by Sahilbabani**
## Pull request checklist
# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have deployed locally to see if issue is fixed
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] Assigned current issues or new issues to PR
-[ ]login and signup page footer alignment changed 
-[ ]image added in home page
-[ ] topnav added
Screenshot (21)
Screenshot (22)
Screenshot (23)
Screenshot (24)

### CODE REVIEW

**Comment by krritik** [comment]
I will review this tomorrow. Since you have added bootstraps file in this too. So no need to merge your  previous PR.

**Comment by krritik** [comment]
Is this a WIP(work in progress) PR or a complete PR
And there are also some merge confilcts, resolve them.

**Comment by Sahilbabani** [comment]
its is in wip pr

**Comment by Sahilbabani** [comment]
Are those conflicts resolved?

**Comment by krritik** [comment]
No, but you can do it later(not necessary now), just make sure to resolve conflicts before final PR. And also remind me, when PR is ready to merge.

**Comment by Sahilbabani** [comment]
I would like change layout of staff_login page

**Comment by krritik** [comment]
You can work on that too, but I cannot assign two issues at the same time. If you want to do that first, you are free to do it.

**Pull request closed without merging**
