### PR TITLE
Solving Issue #6

### PR DESCRIPTION
**Pull request by VarthanV**
I have written the view handler and template for editing the user Info. Suggestion on this regard from the mentor will be helpful. Thanks!

Screenshot 2019-12-07 at 7 55 55 AM
Screenshot 2019-12-07 at 7 55 50 AM
Screenshot 2019-12-07 at 7 55 40 AM

### CODE REVIEW

**Comment by krritik** [comment]
user should not be able to change the username, it should be unique

**Comment by VarthanV** [comment]
> user should not be able to change the username, it should be unique

Sure I will make the changes

**Comment by VarthanV** [comment]
I have made the necessary changes please do review

**Comment by krritik** [comment]
create a redirect button "home" from "edit user"
**Note:** Never send a PR from master branch, because your master branch will be overwritten while resolving the commit. So you will get different commit history

**Comment by VarthanV** [comment]
I have made the changes next time ill not send a PR from the master branch. Thanks for the advice

**Comment by krritik** [comment]
Home should have the URL of 'profile' and not 'home' because home redirects to the login page. So the user has to login again. 
This problem may have arisen due to ambiguous meaning of home. I will try to create an issue for that.
Now you just assign the profile URL.

**Comment by krritik** [comment]
Screenshot from 2019-12-07 10-12-45
can you make the home button look like this?

**Comment by VarthanV** [comment]
Yes i will do it

**Comment by VarthanV** [comment]
I have made the necessary changes

**Review by VarthanV — COMMENTED** [review]
Please do review

**Comment by krritik** [comment]
I will review it by tonight

**Comment by krritik** [comment]
looks fine 
solved issue #6

**Pull request merged**
