### PR TITLE
Fix : Roomdetails URL now working. Also fixed the Detail button width

### PR DESCRIPTION
**Pull request by Rits1272**
## Pull request checklist
# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have deployed locally to see if issue is fixed
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Assigned current issues or new issues to PR

### CODE REVIEW

**Comment by Rits1272** [comment]
Fixes #34. Please review @krritik

**Comment by Rits1272** [comment]
@krritik can you add more backend issues so that I can start working on them?

**Comment by krritik** [comment]
@Rits1272 these days, I am a bit busy. I will try to add some issues. Till then, you can create some issues if needed and work on that.

**Comment by krritik** [comment]
Can you explain what was the error?

**Comment by Rits1272** [comment]
Earlier when you click on the **Details** button, it simply redirected you to the index page (profile page). Now it shows you the details of the room

**Comment by krritik** [comment]
ok got it

**Pull request merged**
