### PR TITLE
changed url https://nest4guest.herokuapp.com/home to nest4guest.herok…

### PR DESCRIPTION
**Pull request by mac912**
…uapp.com/ andchanged incorrect title of the page

## Pull request checklist
# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have deployed locally to see if issue is fixed
- [x] I have commented my code, particularly in hard-to-understand areas

 

 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

### CODE REVIEW

**Comment by mac912** [comment]
I changed URL and incorrect title

**Comment by krritik** [comment]
Looks fine

**Comment by krritik** [comment]
assign issues it solved

**Comment by krritik** [comment]
also update the readme, like the url for the home page.
**Note:** Never send a PR from master branch, because your master branch will be overwritten while resolving the commit. So you will get different commit history

**Comment by mac912** [comment]
ok

**Comment by krritik** [comment]
update the readme and there are some confilcts reslove them, then only I will be able to merge it
@mac912

**Pull request merged**
