### PR TITLE
Add : Implemented Staff Login and its permissions

### PR DESCRIPTION
**Pull request by Rits1272**
## Pull request checklist
# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have deployed locally to see if issue is fixed
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Assigned PR to current issues it resolved or create new issue related to it

### CODE REVIEW

**Comment by Rits1272** [comment]
Fix :  Also added verbose plural names for the django models

**Comment by krritik** [comment]
assign the issue number

**Comment by Rits1272** [comment]
Solved issues :  #8 and #16.

**Comment by krritik** [comment]
Note: Never send a PR from master branch, because your master branch will be overwritten while resolving the commit. So you will get different commit history

**Comment by Rits1272** [comment]
Okay so should I make PR again from a different branch?

**Comment by krritik** [comment]
I will merge it after reviewing it. From next time, be sure to send PR from a different branch.

**Comment by krritik** [comment]
Currently, the staff can only add and delete rooms but could not see them. Add view option too.

**Comment by Rits1272** [comment]
Added Staff view rooms functionality. Please review @krritik

**Comment by krritik** [comment]
looks fine

**Pull request merged**
