### PR TITLE
Added the About Us page

### PR DESCRIPTION
**Pull request by Suchana34**
## Pull request checklist
# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have deployed locally to see if issue is fixed
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Assigned current issues or new issues to PR

### CODE REVIEW

**Comment by Suchana34** [comment]
Added and designed the About Us page.

**Comment by Suchana34** [comment]
I have designed the details of the guesthouses by the Flip- Card CSS template.

**Comment by krritik** [comment]
A screenshot of the about page will be useful

**Comment by Suchana34** [comment]
Screenshot (287)

**Comment by Suchana34** [comment]
Screenshot (288)

**Comment by Suchana34** [comment]
Screenshot (289)

**Comment by Suchana34** [comment]
Screenshot (290)

**Comment by Suchana34** [comment]
Screenshot (291)

**Comment by Suchana34** [comment]
I have actually made the about us page based on the frontend design existing currently. As the frontend updates, I will update the page accordingly.

**Comment by krritik** [comment]
@Suchana34 
**NOTE**:  Never send a PR from the master branch, because your master branch will be overwritten while resolving the commit. So you will get different commit history

**Comment by krritik** [comment]
I will merge it now but do remember from next time while sending PR

**Comment by Suchana34** [comment]
Thank you for the advice. I will surely look after it from next time.

**Pull request merged**
